apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: devvault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: us-central1-docker.pkg.dev/devvault-b3fd84/devvault/backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: devvault-secrets
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: devvault-secrets
                  key: DB_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: devvault-secrets
                  key: JWT_SECRET
            - name: GEMINI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: devvault-secrets
                  key: GEMINI_API_KEY
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: devvault-secrets
                  key: GOOGLE_CLIENT_ID
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: devvault-secrets
                  key: GOOGLE_CLIENT_SECRET
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-service:5432/devvault
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 15
            failureThreshold: 5
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: devvault
spec:
  selector:
    app: backend
  ports:
    - port: 8080
      targetPort: 8080
